### ISSUE TITLE
Passing extra args to sshuttle

### ISSUE THREAD

**Issue by Izikd** [flashashen/no-YOU-talk-to-the-hand#5]
Can you add more args to be passed to sshuttle, probably better per tunnel.

For instance, one useful flag for sshuttle is "--no-latency-control" that fuels up the bandwidth.
https://sshuttle.readthedocs.io/en/stable/manpage.html#cmdoption-sshuttle-no-latency-control

**Comment by flashashen** [comment]
yes, its a good idea. I'm considering taking sshuttle args in a single config element 'sshuttle_args' as follows:

```
  etun:
    proxy:
      host: 192.168.1.3
      sshuttle_args: --no-latency-control --syslog
```

the risk with this approach is that some options are incompatible with this project such as '--daemon' since supervisord wants processes to run in the foreground. Anyway, i'm inclined to take the risk and leave the power with the user. 

thoughts?
